# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    # Required Properties:
    table_id: creative_stats

    # Description of the table
    description: "creative_stats dataset"

dag:
  initialize:
    dag_id: creative_stats
    default_args:
      owner: "Google"

      # When set to True, keeps a task from getting triggered if the previous schedule for the task hasn’t succeeded
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@daily"  
    catchup: False
    default_view: graph

  tasks:
    - operator: "KubernetesPodOperator"

      # Task description
      description: "Run CSV transform within kubernetes pod"

      args:

        task_id: "creative_stats_transform_csv"

        startup_timeout_seconds: 600

        # The name of the pod in which the task will run. This will be used (plus a random suffix) to generate a pod id
        name: "creative_stats"

        # The namespace to run within Kubernetes. Always set its value to "default" because we follow the guideline that KubernetesPodOperator will only be used for very light workloads, i.e. use the Cloud Composer environment's resources without starving other pipelines.
        namespace: "default"

        image_pull_policy: "Always"

        # Docker images will be built and pushed to GCR by default whenever the `scripts/generate_dag.py` is run. To skip building and pushing images, use the optional `--skip-builds` flag.
        image: "{{ var.json.google_political_ads.container_registry.run_csv_transform_kub_creative_stats }}"

        # Set the environment variables you need initialized in the container. Use these as input variables for the script your container is expected to perform.
        env_vars:
          SOURCE_URL: "https://storage.googleapis.com/transparencyreport/google-political-ads-transparency-bundle.zip"
          SOURCE_FILE: "files/data.zip"
          FILE_NAME: "google-political-ads-transparency-bundle/google-political-ads-creative-stats.csv"
          TARGET_FILE: "files/data_output.csv"
          TARGET_GCS_BUCKET: "{{ var.json.shared.composer_bucket }}"
          TARGET_GCS_PATH: "data/google_political_ads/creative_stats/data_output.csv"

        # Set resource limits for the pod here. For resource units in Kubernetes, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes
        resources:
          request_memory: "2G"
          request_cpu: "1"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"

      args:
        task_id: "load_creative_stats_to_bq"

        # The GCS bucket where the CSV file is located in.
        bucket: "{{ var.json.shared.composer_bucket }}"

        # The GCS object path for the CSV file
        source_objects: ["data/google_political_ads/creative_stats/data_output.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "google_political_ads.creative_stats"

        # Use this if your CSV file contains a header row
        skip_leading_rows: 1

        # How to write data to the table: overwrite, append, or write if empty
        # See https://cloud.google.com/bigquery/docs/reference/auditlogs/rest/Shared.Types/WriteDisposition
        write_disposition: "WRITE_TRUNCATE"

        # The BigQuery table schema based on the CSV file. For more info, see
        # https://cloud.google.com/bigquery/docs/schemas.
        # Always use snake_case and lowercase for column names, and be explicit,
        # i.e. specify modes for all columns.

        schema_fields:
          - name        : "ad_id"
            type        : "string"
            description : "Unique id for a specific election ad."
            mode        : "nullable"
          - name        : "ad_url"
            type        : "string"
            description : "URL to view the election ad in the election Advertising on Google report."
            mode        : "nullable"
          - name        : "ad_type"
            type        : "string"
            description : "The type of the ad. Can be TEXT VIDEO or IMAGE."
            mode        : "nullable"
          - name        : "regions"
            type        : "string"
            description : "The regions that this ad is verified for or were served in."
            mode        : "nullable"
          - name        : "advertiser_id"
            type        : "string"
            description : "ID of the advertiser who purchased the ad."
            mode        : "nullable"
          - name        : "advertiser_name"
            type        : "string"
            description : "Name of advertiser."
            mode        : "nullable"
          - name        : "ad_campaigns_list"
            type        : "string"
            description : "IDs of all election ad campaigns that included the ad."
            mode        : "nullable"
          - name        : "date_range_start"
            type        : "date"
            description : "First day a election ad ran and had an impression."
            mode        : "nullable"
          - name        : "date_range_end"
            type        : "date"
            description : "Most recent day a election ad ran and had an impression."
            mode        : "nullable"
          - name        : "num_of_days"
            type        : "integer"
            description : "Total number of days a election ad ran and had an impression."
            mode        : "nullable"
          - name        : "impressions"
            type        : "string"
            description : "Number of impressions for the election ad. Impressions are grouped into several buckets ≤ 10k 10k–100k 100k–1M 1M–10M > 10M."
            mode        : "nullable"
          - name        : "spend_usd"
            type        : "string"
            description : "[DEPRECATED] This field is deprecated in favor of specifying the lower and higher spend bucket bounds in separate Spend_Range_Min and Spend_Range_Max columns."
            mode        : "nullable"
          - name        : "first_served_timestamp"
            type        : "timestamp"
            description : "The timestamp of the earliest impression for this ad."
            mode        : "nullable"
          - name        : "last_served_timestamp"
            type        : "timestamp"
            description : "The timestamp of the most recent impression for this ad."
            mode        : "nullable"
          - name        : "age_targeting"
            type        : "string"
            description : "Age ranges included in the ad's targeting"
            mode        : "nullable"
          - name        : "gender_targeting"
            type        : "string"
            description : "Genders included in the ad's targeting."
            mode        : "nullable"
          - name        : "geo_targeting_included"
            type        : "string"
            description : "Geographic locations included in the ad's targeting."
            mode        : "nullable"
          - name        : "geo_targeting_excluded"
            type        : "string"
            description : "Geographic locations excluded in the ad's targeting."
            mode        : "nullable"
          - name        : "spend_range_min_usd"
            type        : "integer"
            description : "Lower bound of the amount in USD spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_usd"
            type        : "integer"
            description : "Upper bound of the amount in USD spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_eur"
            type        : "integer"
            description : "Lower bound of the amount in EUR spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_eur"
            type        : "integer"
            description : "Upper bound of the amount in EUR spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_inr"
            type        : "integer"
            description : "Lower bound of the amount in INR spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_inr"
            type        : "integer"
            description : "Upper bound of the amount in INR spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_bgn"
            type        : "integer"
            description : "Lower bound of the amount in BGN spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_bgn"
            type        : "integer"
            description : "Upper bound of the amount in BGN spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_hrk"
            type        : "integer"
            description : "Lower bound of the amount in HRK spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_hrk"
            type        : "integer"
            description : "Upper bound of the amount in HRK spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_czk"
            type        : "integer"
            description : "Lower bound of the amount in CZK spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_czk"
            type        : "integer"
            description : "Upper bound of the amount in CZK spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_dkk"
            type        : "integer"
            description : "Lower bound of the amount in DKK spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_dkk"
            type        : "integer"
            description : "Upper bound of the amount in DKK spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_huf"
            type        : "integer"
            description : "Lower bound of the amount in HUF spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_huf"
            type        : "integer"
            description : "Upper bound of the amount in HUF spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_pln"
            type        : "integer"
            description : "Lower bound of the amount in PLN spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_pln"
            type        : "integer"
            description : "Upper bound of the amount in PLN spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_ron"
            type        : "integer"
            description : "Lower bound of the amount in RON spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_ron"
            type        : "integer"
            description : "Upper bound of the amount in RON spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_sek"
            type        : "integer"
            description : "Lower bound of the amount in SEK spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_sek"
            type        : "integer"
            description : "Upper bound of the amount in SEK spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_gbp"
            type        : "integer"
            description : "Lower bound of the amount in GBP spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_gbp"
            type        : "integer"
            description : "Upper bound of the amount in GBP spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_min_nzd"
            type        : "integer"
            description : "Lower bound of the amount in NZD spent by the advertiser on the election ad."
            mode        : "nullable"
          - name        : "spend_range_max_nzd"
            type        : "integer"
            description : "Upper bound of the amount in NZD spent by the advertiser on the election ad."
            mode        : "nullable"


  graph_paths:
    - "creative_stats_transform_csv >> load_creative_stats_to_bq"




    